version: '3.1'

services:
  
  wordpress:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: diegotorres95/wordpress:v1
    restart: always
    ports:
        - 8089:80
    volumes:
        - ./html:/var/www/html
    env_file:
        - ./.envs/.wordpress

